### ISSUE TITLE
Allow using custom trust anchor with `drg stream`

### ISSUE THREAD

**Issue by ctron** [drogue-iot/drg#143] opened 2022-06-28 13:35 UTC
Currently `drg stream` with `wss://` (TLS) requires a valid system trust anchor.

It should be possible to:

* [ ] Provide a custom trust anchor (e.g. `--ca-cert <file>`)
* [x] Allow disabling TLS validation (`--insecure`)

**Comment by jbtrystram** [comment] 2022-07-06 10:06
closing this, as it's a duplicate of https://github.com/drogue-iot/drg/issues/29

**Closed by jbtrystram** 2022-07-06 10:06 UTC
Labels: enhancement
