### ISSUE TITLE
Provide `drg` commands to set passwords and gateways.

### ISSUE THREAD

**Issue by ctron** [drogue-iot/drg#69] opened 2021-05-18 12:43 UTC
The release tracking issue:

* [ ] Specify API
* [x] #93
* [x] Allow setting a gateway
…

**Comment by jbtrystram** [comment] 2021-05-18 14:03
duplicate of https://github.com/drogue-iot/drg/issues/41 ?

**Comment by ctron** [comment] 2021-05-18 14:48
Tracking issue … for the project board.

**Closed** 2021-08-12 08:25 UTC
